name: CI - Playwright + Lighthouse Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build Next.js app
      run: yarn build
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
        AI_ENABLED: true
        AI_PROVIDER: openai
        AI_MAX_CALLS_PER_DAY: 10
        AI_MAX_TOKENS_PER_MONTH: 100000
    
    - name: Start Next.js app
      run: yarn start &
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
        AI_ENABLED: true
        AI_PROVIDER: openai
        AI_MAX_CALLS_PER_DAY: 10
        AI_MAX_TOKENS_PER_MONTH: 100000
    
    - name: Wait for app to be ready
      run: npx wait-on http://localhost:3000 --timeout 60000
    
    - name: Run Playwright tests
      run: npx playwright test
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
    
    - name: Install Lighthouse CI
      run: npm install -g @lhci/cli@0.12.x
    
    - name: Run Lighthouse CI
      run: lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lighthouse-report
        path: .lighthouseci/
        retention-days: 30

  mobile-test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build Next.js app
      run: yarn build
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
    
    - name: Start Next.js app
      run: yarn start &
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
    
    - name: Wait for app to be ready
      run: npx wait-on http://localhost:3000 --timeout 60000
    
    - name: Run Mobile Playwright tests
      run: npx playwright test --project="Mobile Chrome"
      env:
        NEXT_PUBLIC_BASE_URL: http://localhost:3000
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mobile-playwright-report
        path: playwright-report/
        retention-days: 30